[package]
name = "ktls"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]
edition = "2018"

[dependencies]
libc = "*"
byteorder = "*"

[dev-dependencies]
webpki = "*"
webpki-roots = "*"
rustls = { git = "https://github.com/quininer/rustls", branch = "ktls" }
